name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"

  date_job:
    runs-on: ubuntu-latest
    steps:
      - name: Now it is
        run: |
          date

  directory_job:
    runs-on: ubuntu-latest
    steps:
      - name: Directory contents
        run: |
          ls
